# .goreleaser.yml
before:
  hooks:
    - go mod tidy

builds:
  - env: [ "CGO_ENABLED=1" ]
    binary: gocobra
    goos:
    - darwin
    - linux
    goarch:
    - amd64
    - arm64

kos:
  - repository: ghcr.io/timoniersystems/gocobra
    tags:
    - '{{.Version}}'
    - latest
    bare: true
    preserve_import_paths: false
    platforms:
    - linux/amd64
    - linux/arm64
    sbom: cyclonedx
