name: goreleaser

on:
  push:
    tags:
      - '*'
  # pull_request:
  # push:

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
      - name: Install Syft
        uses: anchore/sbom-action/download-syft@v0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Install Cosign
        uses: sigstore/cosign-installer@main
      - name: Set up Cosign variables
        env: 
          COSIGN_PWD: ${{ secrets.COSIGN_PRIVATE_KEY_PASSWORD }}
        shell: bash
        run: |
          echo ${{ secrets.COSIGN_KEY_BASE64 }} | base64 -d > /tmp/cosign.key
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        id: goreleaser
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Show goreleaser metadata
        shell: bash
        run: |
          METADATA=${{ steps.goreleaser.outputs.metadata }}
          echo $METADATA
      - name: Sign generated Docker image with Cosign
        shell: bash
        run: |
          IMAGE_TAG=$(jq -r '.tag' <<< \'${{ steps.goreleaser.outputs.metadata }}\')
          IMAGE_NAME=ghcr.io/timoniersystems/gocobra
          cosign sign --key env://COSIGN_PRIVATE_KEY ${IMAGE_NAME}:${IMAGE_TAG}
        env:
          COSIGN_PRIVATE_KEY: ${{secrets.COSIGN_PRIVATE_KEY}}
          COSIGN_PASSWORD: ${{secrets.COSIGN_PRIVATE_KEY_PASSWORD}}

